[project]
name = "quant-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "pydantic>=2.11.2",
    "setuptools>=78.1.0",
    "wheel>=0.45.1",
]
